#pragma once

typedef enum {
    WifiMarauderEventRefreshConsoleOutput = 0,
    WifiMarauderEventStartConsole,
    WifiMarauderEventStartKeyboard,
    WifiMarauderEventSaveSourceMac,
    WifiMarauderEventSaveDestinationMac,
    WifiMarauderEventStartSettingsInit,
    WifiMarauderEventStartSniffPmkidOptions,
    // Marauder's Mate: live scanall feature
    WifiMarauderEventStartScanLive,
    WifiMarauderEventScanApSelected,
    WifiMarauderEventScanRescan,
    WifiMarauderEventScanAction,
    WifiMarauderEventScanAttacks,
    WifiMarauderEventScanStations,
    WifiMarauderEventScanFoxHunt,
    WifiMarauderEventScanJoin,
    WifiMarauderEventScanHosts,
    WifiMarauderEventScanDisconnect,
    WifiMarauderEventStartBeaconMon,
    WifiMarauderEventStartProbeMon,
    WifiMarauderEventStartDeauthMon,
    WifiMarauderEventStartRogueMon,
    WifiMarauderEventStartPineappleMon,
    WifiMarauderEventStartPwnagotchiMon,
    WifiMarauderEventStartGpsData,
    WifiMarauderEventStartGpsSats,
    WifiMarauderEventStartDeviceInfo,
    WifiMarauderEventDeviceRedetect,
    WifiMarauderEventGpsProbe, // Device Info: probe direct GPS on LPUART (G0)
    WifiMarauderEventOpenLedPicker,
    WifiMarauderEventOpenRebootConfirm,
    WifiMarauderEventOpenSettingsMenu,
    WifiMarauderEventOpenCategory,
    WifiMarauderEventOpenSpoof,
    WifiMarauderEventHostPortScan,
    WifiMarauderEventStaSelected,
    WifiMarauderEventStaDeauth,
    WifiMarauderEventStaFoxHunt,
    WifiMarauderEventPrevScene
} WifiMarauderCustomEvent;
